
name: einvoice-provide

services:
  mongo:
    image: mongo:latest
    container_name: mongodb-server
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./docker/docker_data/mongodb_data:/data/db
    restart: unless-stopped