name: einvoice-provide

networks:
  einvoice-nw:
    driver: bridge
    name: einvoice-nw

services:
  mongo:
    image: mongo:latest
    container_name: mongodb-server
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./docker/docker_data/mongodb_data:/data/db
    networks:
      - einvoice-nw
    restart: unless-stopped

  postgres:
    image: postgres:18
    container_name: postgres-server
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: einvoice-app
    volumes:
      - ./docker/docker_data/postgres_data:/var/lib/postgresql
    restart: unless-stopped
    networks:
      - einvoice-nw

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-server
    restart: unless-stopped
    ports:
      - '8080:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    networks:
      - einvoice-nw
    volumes:
      - ./docker/docker_data/pgadmin_data:/var/lib/pgadmin

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-server
    restart: unless-stopped
    command: ['start-dev']
    ports:
      - '8180:8080'
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    networks:
      - einvoice-nw
    volumes:
      - ./docker/docker_data/keycloak_data:/opt/keycloak/data
